/*
===============================================================================
DDL Script: Create Bronze Tables
===============================================================================
Script Purpose:
    This script creates tables in the 'bronze' schema, dropping existing tables 
    if they already exist.
	  Run this script to re-define the DDL structure of 'bronze' Tables
===============================================================================
*/


USE h_db
GO

IF OBJECT_ID('bronze.erp_sys_item', 'U') IS NOT NULL
    DROP TABLE bronze.erp_sys_item;
GO

CREATE TABLE bronze.erp_sys_item
(
    itemean                 CHAR(13),
    itemclass               SMALLINT,
    section                 SMALLINT,
    itemgroup               SMALLINT,
    department              SMALLINT,
    a_name                  VARCHAR(50),
    l_name                  VARCHAR(50),
    shortname               VARCHAR(16),
    flavor                  VARCHAR(50),
    brand                   SMALLINT,
    producerno              INT,
    category                SMALLINT,
    referenceno             CHAR(30),
    color                   SMALLINT,
    size                    DECIMAL(7,2),
    measure                 SMALLINT,
    hyper_market            SMALLINT,
    class_a                 SMALLINT,
    home_delivery           SMALLINT,
    storeinterval           SMALLINT,
    shelfinterval           SMALLINT,
    goodstype               SMALLINT,
    itemtype                SMALLINT,
    profit                  DECIMAL(6,2),
    loss_rate               DECIMAL(7,2),
    expirycheck             SMALLINT,
    class_c                 SMALLINT,
    range_cal               SMALLINT,
    ordered_from            SMALLINT,
    zone                    SMALLINT,
    bin_location            VARCHAR(20),
    class_b                 SMALLINT,
    status                  SMALLINT,
    statusdate              SMALLDATETIME,
    userid                  INT,
    transid                 SMALLINT,
    pluupd                  SMALLINT,
    transdate               SMALLDATETIME,
    purchase_date           SMALLDATETIME,
    whole_sale              SMALLINT,
    nationalty              SMALLINT,
    big_supermarket         SMALLINT,
    module_group            SMALLINT,
    module_no               SMALLINT,
    basic_item              SMALLINT,
    entry_date              SMALLDATETIME,
    active                  SMALLINT,
    price_class             SMALLINT,
    transtype               SMALLINT,
    item_image              VARCHAR(100),
    sales_tax               SMALLINT,
    add_tax                 SMALLINT,
    Tax_level               SMALLINT,
    Season                  SMALLINT,
    Isdraft                 SMALLINT,
    IsConsumed              SMALLINT,
    Modified_date           DATE,
    Isloaded                SMALLINT,
    Loadedby                INT,
    Loadeddate              DATETIME,
    IsSalesOnLine            SMALLINT,
    AdditionalInfo          VARCHAR(255),
    Notes                   VARCHAR(500),
    Isserialized             SMALLINT,
    IsMaterial_Internal     SMALLINT,
    IsMaterial_Outside      SMALLINT,
    IsFinalProduct          SMALLINT,
    IstemperatureNeed       SMALLINT,
    Internal_manufacturing  SMALLINT,
    Outside_manufacturing   SMALLINT,
    Material                SMALLINT,
    Warranty_Period         SMALLINT,
    Warranty_Type           SMALLINT,
    Warranty_percentage     NUMERIC(18,3),
    Over_Rate               NUMERIC(18,3),
    Item_Unit               SMALLINT,
    Item_Piece              SMALLINT,
    Item_Put_ReorderQty     SMALLINT,
    ItemPartNo              VARCHAR(100),
    ISBN                    VARCHAR(100),
    Author                  INT,
    Publisher               INT,
    Createdby               INT,
    Reserved1               VARCHAR(500),
    Reserved2               VARCHAR(500),
    Reserved3               VARCHAR(500),
    Reserved4               NUMERIC(18,3),
    Reserved5               NUMERIC(18,3),
    Reserved6               DATETIME,
    Reserved7               DATETIME,
    Reserved8               INT,
    Reserved9               INT,
    Reserved10              INT,
    Reserved11              DATETIME,
    Reserved12              DATETIME,
    Reserved13              INT,
    Reserved14              INT,
    Reserved15              INT,
    SourceRowVersion        BIGINT,
    CreatedRowVersion       BIGINT,
    CreatedAt               INT,
    ModifiedAt              INT,
    DateCreated             DATETIME,
    DateModified            DATETIME,
    Data                    NVARCHAR(MAX),

    -- 🔧 Bronze technical columns
    bronze_load_datetime    DATETIME DEFAULT GETDATE(),
    bronze_source_system    VARCHAR(50) DEFAULT 'ERP',
);
